import { Step } from '../../interfaces/step';

export const spin4deadStep: Step = {
  payload: {
    beforeSymbols: [
      { id: 5, indices: [0], properties: { multiplier: 0.1 } },
      { id: 6, indices: [1], properties: { multiplier: 0.1 } },
      { id: 7, indices: [2], properties: { multiplier: 0.1 } },
      { id: 8, indices: [3], properties: { multiplier: 1 } },
      { id: 5, indices: [4], properties: { multiplier: 0.1 } },
      { id: 5, indices: [5], properties: { multiplier: 0.1 } },
      { id: 6, indices: [6], properties: { multiplier: 0.1 } },
      { id: 7, indices: [7], properties: { multiplier: 0.1 } },
      { id: 8, indices: [8], properties: { multiplier: 1 } },
      { id: 5, indices: [9], properties: { multiplier: 0.1 } },
      { id: 5, indices: [10], properties: { multiplier: 0.1 } },
      { id: 6, indices: [11], properties: { multiplier: 0.1 } },
      { id: 7, indices: [12], properties: { multiplier: 0.1 } },
      { id: 8, indices: [13], properties: { multiplier: 1 } },
      { id: 5, indices: [14], properties: { multiplier: 0.1 } },
      { id: 5, indices: [15], properties: { multiplier: 0.1 } },
      { id: 6, indices: [16], properties: { multiplier: 0.1 } },
      { id: 7, indices: [17], properties: { multiplier: 0.1 } },
      { id: 8, indices: [18], properties: { multiplier: 1 } },
      { id: 5, indices: [19], properties: { multiplier: 0.1 } },
    ],
    afterSymbols: [
      { id: 5, indices: [0], properties: { multiplier: 0.1 } },
      { id: 6, indices: [1], properties: { multiplier: 0.1 } },
      { id: 7, indices: [2], properties: { multiplier: 0.1 } },
      { id: 8, indices: [3], properties: { multiplier: 1 } },
      { id: 5, indices: [4], properties: { multiplier: 0.1 } },
      { id: 5, indices: [5], properties: { multiplier: 0.1 } },
      { id: 6, indices: [6], properties: { multiplier: 0.1 } },
      { id: 7, indices: [7], properties: { multiplier: 0.1 } },
      { id: 8, indices: [8], properties: { multiplier: 1 } },
      { id: 5, indices: [9], properties: { multiplier: 0.1 } },
      { id: 5, indices: [10], properties: { multiplier: 0.1 } },
      { id: 6, indices: [11], properties: { multiplier: 0.1 } },
      { id: 7, indices: [12], properties: { multiplier: 0.1 } },
      { id: 8, indices: [13], properties: { multiplier: 1 } },
      { id: 5, indices: [14], properties: { multiplier: 0.1 } },
      { id: 5, indices: [15], properties: { multiplier: 0.1 } },
      { id: 6, indices: [16], properties: { multiplier: 0.1 } },
      { id: 7, indices: [17], properties: { multiplier: 0.1 } },
      { id: 8, indices: [18], properties: { multiplier: 1 } },
      { id: 5, indices: [19], properties: { multiplier: 0.1 } },
    ],
    nextStepType: 1,
    events: [],
  },
  cost: 0,
  stepWin: 100,
  totalWin: 0,
  type: 1,
};
